language: php

php: [5.3, 5.4, 5.5]

env:
  - SYMFONY_VERSION='2.2.*'
  - SYMFONY_VERSION='2.3.*'
  - SYMFONY_VERSION='2.4.*'

before_script:
  - composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install --prefer-source --no-interaction --no-progress

script:
  - vendor/bin/behat -c=testapp/behat.yml -p=simple
  - vendor/bin/behat -c=testapp/behat.yml -p=web
